[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_status]
ahead = 'â‡¡${count}'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
deleted = 'ğŸ—‘ \($count\)'
behind = 'â‡£${count}'
staged = '[++\($count\)](fg:#769ff0 bg:#394260)'
format = '$ahead_behind '
